### ISSUE TITLE
next game level logics

### ISSUE THREAD

**Issue by rugged-bl** [inwords/InWords#35]
сейчас вообще раза 3 подряд был 1 уровень
на 3 уровень попала попытки с 6
потому что перекидывало между 1 и 2 уровнями постоянно

**когда прилетают звездочки, получается новый gamelevelinfo, его индекс=? => ошибка**

**Comment by Alword** [comment]
Предлагаю сформировать массив id уровней, отсортировать по номеру уровня, объявить индекс текущего уровня и просто прибавлять его при нажатии на кнопку "следующий уровень".

**Comment by rugged-bl** [comment]
> 
> 
> Предлагаю сформировать массив id уровней, отсортировать по номеру уровня, объявить индекс текущего уровня и просто прибавлять его при нажатии на кнопку "следующий уровень".

Будет исправлено в следующей версии
